# Generated by Django 5.1.15 on 2026-06-17 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(db_index=True, max_length=160)),
                ('category', models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('building_materials', 'Building Materials'), ('fuel', 'Fuel'), ('electronics', 'Electronics')], db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='marketprices.market')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
            options={
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['product', 'date'], name='marketprice_product_66361c_idx'), models.Index(fields=['category', 'region', 'date'], name='marketprice_categor_47b7ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'market', 'unit', 'date'), name='unique_price_observation')],
            },
        ),
    ]
