# Generated by Django 5.1.15 on 2026-06-17 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('supply', 'Supply Request'), ('buyer', 'Buyer Request'), ('investment', 'Investment Opportunity'), ('partnership', 'Partnership Opportunity'), ('distribution', 'Distribution Opportunity')], db_index=True, max_length=15)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(blank=True, db_index=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('open', 'Open'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='businesses.business')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type', 'status'], name='opportuniti_type_41b931_idx'), models.Index(fields=['region', 'industry'], name='opportuniti_region__bb8065_idx')],
            },
        ),
    ]
