# Generated by Django 5.1.15 on 2026-06-17 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('buyer', 'Interested Buyer'), ('supplier', 'Supplier Lead'), ('partnership', 'Partnership Lead')], db_index=True, default='buyer', max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=12)),
                ('score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score', '-created_at'),
                'indexes': [models.Index(fields=['business', 'status'], name='leads_lead_busines_912f9f_idx')],
            },
        ),
    ]
