# Generated by Django 5.1.15 on 2026-06-17 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(db_index=True, max_length=200)),
                ('tender_number', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('private', 'Private')], db_index=True, max_length=12)),
                ('closing_date', models.DateField(blank=True, db_index=True, null=True)),
                ('documents_url', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='tenders/')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('external', 'External Feed')], default='manual', max_length=10)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sector', 'is_active'], name='tenders_ten_sector_c88dc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tender_number', 'organization'), name='unique_tender_per_org')],
            },
        ),
    ]
